---

# Playbook to create AWS instances, basic playbook to call build script

- hosts: jumpbox
  vars:
    catalog_name: OPENTLC Automation
    item_name: Three Tier Application

# Create AWS instances
  tasks:
  - name: Create 3Tier application AWS instances via supplied script
    #command: source credential.rc ; ./order_svc.sh -c '{{ catalog_name }}' -i '{{ item_name }}' -t 1 -y
    command: source credential.rc ; ./order_svc.sh -c '{{ catalog_name }}' -i '{{ item_name }}' -t 1
    
