---

# Playbook to create Openstack instances, setup networking and security

- hosts: all
  
  roles:
    - openstack_network
    - openstack_keypair
    - openstack_security
    - openstack_flavor

  tasks:
# Create Openstack database instance

  - name: Create 3Tier application database instance
    include_role:
      name: openstack_instance
      vars_from: database.yml

# Create Openstack application1 instance

  - name: Create 3Tier application application1 instance
    include_role:
      name: openstack_instance
      vars_from: application1.yml

# Create Openstack application2 instance

  - name: Create 3Tier application application2 instance
    include_role:
      name: openstack_instance
      vars_from: application2.yml

# Create Openstack frontend instances

  - name: Create 3Tier application frontend instance
    include_role:
      name: openstack_instance
      vars_from: frontend.yml

