---
## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Playbook description:
#
# Destroys OpenStack instances created, this is used for rollback of the deployment in
# Ansible Tower workflow but can also be called from the CLI.
# Due to the complexity of tearing down the OpenStack networking this will remain and only the 
# instances themselves will be destroyed.
#

## Playbook enhancements post PoC:
#
# Variablization for the `openstack_instance` role to use `with_subelements` would reduce the duplication of calling
# this role 3 seperate times, it would also mean adding more components to the application would not require modification to the
# role code in multiple roles - creation and destroy.
#

# Playbook to destroy Openstack instances, leaving networking configured

- hosts: jumpbox
  tasks:

  - name: Destroy 3Tier application database instance
    include_role:
      name: openstack_instance
      tasks_from: destroy_instances
      vars_from: database.yml

  - name: Destroy 3Tier application application1 instance
    include_role:
      name: openstack_instance
      tasks_from: destroy_instances
      vars_from: application1.yml

  - name: Destroy 3Tier application application2 instance
    include_role:
      name: openstack_instance
      tasks_from: destroy_instances
      vars_from: application2.yml

  - name: Destroy 3Tier application frontend instance
    include_role:
      name: openstack_instance
      tasks_from: destroy_instances
      vars_from: frontend.yml

