---
## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Role description:
#
# In memory inventory is created from the deployed OpenStack instances.
# The os_server_facts module is used to collect metadata tags added during the
# instance creation, this is then used to group the instances into application 
# groups.
#

# tasks file for osp-facts
  - name: Fetch Instance Info
    os_server_facts:
     cloud: ospcloud
     region_name: RegionOne
    register: result

  - name: Create host group based on metadata group
    add_host:
      name: "{{ item.public_v4 }}"
      groups: all
    with_items: "{{ result.ansible_facts.openstack_servers }}"

  - name: Create host group based on metadata group
    add_host:
      name: "{{ item.public_v4 }}"
      groups: "{{ item.metadata.group }}"
    with_items: "{{ result.ansible_facts.openstack_servers }}"

  - name: Create host group based on metadata deployment_name
    add_host:
      name: "{{ item.public_v4 }}"
      groups: "{{ item.metadata.deployment_name }}"
    with_items: "{{ result.ansible_facts.openstack_servers }}"

