---
## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Role description:
#
# Creates SSH 2048 Key pair which is then distributed to Nova and then injected into
# newly created instances in ospcloud instance.
#

# Openstack access key setup

  - name: Generate access key files
    user:
      name: "{{ ansible_env.USER }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/ansible_id_rsa

  - name: Distribute SSH key
    os_keypair:
      cloud: ospcloud
      state: present
      name: ansible_ssh
      public_key_file: "{{ ansible_env.HOME }}/.ssh/ansible_id_rsa.pub"
