---
## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Role description:
#
# This role was created as it was found that once the RedHat Openstack Lab was shutdown and restarted
# the instances were not started by default.
# This was not included in the 3Tier Application deployment but was called both via the CLI and added as 
# an Ansible Tower job as an adhoc job.  
#

# Start Openstack server instance

  - name: Checking server instance "{{ instance_name }}" status
    os_server_facts:
      cloud: ospcloud
      server: "{{ instance_name }}"
    register: server_state

  - name: Start server instance "{{ instance_name }}"
    os_server_action:
      action: start
      cloud: ospcloud
      server: "{{ instance_name }}"
      wait: yes
    when: openstack_servers.0.status != "ACTIVE"
